// Generated by packages/cli/scripts/generate-sigil-keys.mjs -- do not edit.
//
// Regenerate with `node scripts/generate-sigil-keys.mjs` from inside
// packages/cli, then `pnpm fmt`. `the committed key set` in
// packages/cli/test/i18n-keys.test.ts fails if this file and the source have
// come apart.

/**
 * Every message the framework itself can print, keyed on its English.
 *
 * 37 keys, which is what a catalog has to carry to translate sigil's own
 * output whole. `sigil check` reads this to say which of them an app's
 * catalogs are missing -- and the other way round, so a reworded English
 * sentence shows up as one missing key and one orphan rather than as silence.
 *
 * It is a *generated* list rather than a hand-kept one for the reason every
 * other derived table here is: a second copy of the English that somebody has
 * to remember to edit is a copy that goes out of date, and the key is the
 * English, so there is nothing else for this to be.
 */
export const SIGIL_KEYS: readonly string[] = [
	'(choices: {0})',
	'(default: {0})',
	'<command>',
	'Alias:',
	'Arguments:',
	'Commands:',
	'Count is too large to be exact: {0}',
	'Error: {0}',
	'Examples:',
	'Extra arguments are not allowed: {0}',
	'Global options:',
	'Integer is too large to be exact: {0}',
	'Invalid JSON: {0}',
	'Invalid boolean: "{0}"',
	'Invalid count: {0}',
	'Invalid date: "{0}"',
	'Invalid integer: {0}',
	'Invalid number: {0}',
	'Invalid value "{0}" for {1}',
	'Missing required arguments: {0}',
	'Missing required options: {0}',
	'Missing value for option {0}',
	'Options:',
	'Print the version',
	'Show help for a command',
	'The command to describe',
	'Unexpected argument "{0}"',
	'Unknown command "{0}"',
	'Unknown option "{0}"',
	'Usage:',
	'Value must be "yes" or "no"',
	'[command]',
	'[options]',
	'argument <{0}>',
	'option {0}',
	'{0} arguments:',
	'{0} options:',
];

/**
 * The 1 of those whose catalog entry is an object of plural categories
 * rather than a string.
 *
 * A catalog may answer either -- a plain string is taken for a language with
 * one form for every count, which is what Japanese, Chinese and Korean have --
 * so this is what a catalog author needs to know rather than something the
 * lookup enforces.
 */
export const SIGIL_PLURAL_KEYS: readonly string[] = ['Alias:'];
