// Generated by scripts/generate-commands.mjs. Do not edit.
//
// The descriptions lifted out of src/commands/, so `sigil --help` can name
// every command without importing one. Regenerate with:
//
//     node scripts/generate-commands.mjs
//
// `the committed route info` in test/commands.test.ts fails if this and the
// command modules have come apart.

import type { RouteInfo } from '@ttylabs/sigil';

export const ROUTE_INFO: Record<string, RouteInfo> = {
	add: {
		desc: 'Copy a component into your app, so you own it',
	},
	build: {
		desc: 'Build an app into a bundle that depends on nothing',
	},
	check: {
		desc: 'Check an app without building it',
	},
	new: {
		desc: 'Create a new app',
	},
};
