import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * What `sigil add` copies.
 *
 * `registry/` is generated by `scripts/generate-registry.mjs` during the build
 * and shipped rather than committed, so this reads the built output the way
 * `dist.test.ts` does and needs a build first.
 *
 * The claim being pinned is narrow and worth stating: an entry is the component
 * this package actually ships, with its imports rewritten to published
 * subpaths, and nothing else changed. Everything below is one half of that.
 */

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const registry = join(root, 'registry');

interface Entry {
	readonly classes: readonly string[];
	readonly desc: string;
	readonly files: readonly { readonly from: string; readonly to: string }[];
	readonly imports: readonly string[];
	readonly registryDeps: readonly string[];
}

interface Manifest {
	readonly entries: Record<string, Entry>;
	readonly name: string;
	readonly version: string;
}

const manifest = JSON.parse(readFileSync(join(registry, 'registry.json'), 'utf-8')) as Manifest;
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf-8')) as {
	exports: Record<string, unknown>;
	files: string[];
	name: string;
	version: string;
};

/** The subpaths the package publishes, as an ejected file would import them. */
const published = new Set(
	Object.keys(pkg.exports)
		.filter((key) => key !== './package.json')
		.map((key) => (key === '.' ? pkg.name : `${pkg.name}/${key.slice(2)}`))
);

const names = Object.keys(manifest.entries);

describe('the registry', () => {
	it('should have been built', () => {
		// a missing registry is a build that did not run, not a passing test
		expect(existsSync(registry), `no registry in ${registry}; run \`pnpm build\``).toBe(true);
		expect(names.length).toBeGreaterThan(0);
	});

	it('should ship with the package', () => {
		// the whole reason it is generated: `files` was `["dist"]`, so the
		// published package carried no component source and `sigil add` had
		// nothing at all to copy
		expect(pkg.files).toContain('registry');
	});

	it('should name the version it came from', () => {
		// an ejected component is only guaranteed to match the API it was ejected
		// from, so the copy has to be able to say which that was
		expect(manifest.name).toBe(pkg.name);
		expect(manifest.version).toBe(pkg.version);
	});

	it.each(names)('should ship every file %s declares', (name) => {
		const entry = manifest.entries[name] as Entry;
		expect(entry.files.length).toBeGreaterThan(0);

		for (const file of entry.files) {
			expect(existsSync(join(registry, file.from)), `${name}: ${file.from} is missing`).toBe(true);
		}
	});

	it.each(names)('should leave no relative import in %s', (name) => {
		// the property that makes an ejected file work at all: a relative
		// specifier means nothing once the file is in somebody else's tree, and
		// it would fail for them rather than here
		for (const file of manifest.entries[name]?.files ?? []) {
			const source = readFileSync(join(registry, file.from), 'utf-8');
			const relative = [...source.matchAll(/\bfrom\s*'(\.[^']*)'/g)].map(([, spec]) => spec);
			expect(relative, `${name} still imports these relatively`).toStrictEqual([]);
		}
	});

	it.each(names)('should import only what the package publishes from %s', (name) => {
		// the rewrite maps onto the `exports` map, so a subpath that stopped
		// being published would leave an entry importing something unresolvable
		for (const spec of manifest.entries[name]?.imports ?? []) {
			expect(published, `${name} imports ${spec}`).toContain(spec);
		}
	});

	it.each(names)('should be the component this package ships, for %s', (name) => {
		// the drift check, and the one that matters most: a registry entry is
		// `src/components/<name>.ts` with its imports rewritten and *nothing
		// else* changed, so an entry that has quietly become a stale fork of the
		// real component fails here rather than shipping.
		//
		// Only the specifier is blanked, rather than whole import lines being
		// dropped: the imported *names* are compared too, and an import may span
		// several lines -- `table.ts` has one, which is what caught the first
		// version of this doing it by line.
		const strip = (source: string): string => source.replaceAll(/\bfrom\s*'[^']*'/g, "from '~'");

		const shipped = readFileSync(join(registry, `${name}.ts`), 'utf-8');
		const source = readFileSync(join(root, 'src', 'components', `${name}.ts`), 'utf-8');

		expect(strip(shipped)).toBe(strip(source));
	});

	it.each(names)('should say what %s can be themed with', (name) => {
		const entry = manifest.entries[name] as Entry;

		// a component styles itself with classes and never with colour props,
		// because a prop beats a sheet per property and a colour written into a
		// template is one a theme cannot reach without `!important`. Listing them
		// is what makes the rule checkable by whoever copied the component in
		expect(entry.classes.length).toBeGreaterThan(0);
		for (const cls of entry.classes) {
			expect(cls).toMatch(/^sigil-[a-z-]+$/);
		}
	});

	it('should describe every entry', () => {
		for (const [name, entry] of Object.entries(manifest.entries)) {
			expect(entry.desc, `${name} has no description`).toBeTruthy();
		}
	});
});
